{% set name = "j6s" %}
{% set version = "1.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/raphidoc/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 71247c06492914fa15a20ca943d6fe57559fd6e3ab043af56951498010eb9222

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation 

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - wheel
  run:
    - python >={{ python_min }}
    - sixs_json

test:
  imports:
    - j6s
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/raphidoc/j6s
  license: MIT
  license_file: LICENSE
  summary: 'Wrapper for the 6S atmospheric radiative transfer model modified with JSON output'

extra:
  recipe-maintainers:
    - raphidoc
